### ISSUE TITLE
Inputs of iOS-app-spider

### ISSUE THREAD

**Issue by cl0udz** [CodingForMoney/ios-app-spider#1]
Thanks for your work. It's quite helpful for ios application analyzers.

In ios/server/pre-process.py, it seems a list of apps(load_excel_path and app_json_file) is needed. I've searched a lot on Google but nothing valuable found. Could you give me some advice on how to get it?

**Comment by CodingForMoney** [comment]
`load_excel_path` is a input Excel file which contains some information of APPs that we want analyze. In this Excel file , the most import information is the `APP ID`. This repository don't contain this part of crawler to get a APP list with `APP ID`. `iOS-app-spider` just download the `.ipa` file and analyze the URL Scheme.

`app_json_file` is putting in the `./input/` directory. This file is output file In `pre-process.py`. But it is input file in `server.py`.

**Comment by cl0udz** [comment]
Thanks for the reply.

Based on your explanation, I construct a xls file which contains needed info. Finally it works now.

PS: Based on my understanding, your code is actually a tool to automatically find URL scheme in given apps. So I suggest you to change the name to something like "URL scheme spider/collector". Maybe in most cases, we consider an app-spider as a tool to download applications.

**Comment by CodingForMoney** [comment]
yes, `ios-app-spider` is not a good name ,even there are some codes to crawl Android APP info.
