### ISSUE TITLE
it seems it's not working anymore

### ISSUE THREAD

**Issue by huliang2016** [CodingForMoney/ios-app-spider#2]
I got this error while using this code.
**Error Content:** requests.exceptions.ConnectionError: HTTPSConnectionPool(host='jsondata.25pp.com', port=443): Max retries exceeded with url: /jsondata.html (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001B93BBED048>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))

waiting for your reply, thanks~

**Comment by CodingForMoney** [comment]
I did tried, there is no problem.

There are two phases in this crawler:

1.  Get some information and try downloading in the site `*.25pp.com` .
2. Tweak to perform operation on the `App Store`  to download the `ipa` file.

So you should check the access to this site [25pp.com](https://25pp.com).

**Comment by huliang2016** [comment]
After check the internet, I can access [25pp.com](https://www.25pp.com/), but I can't access this url: [https://jsondata.25pp.com/jsondata.html](https://jsondata.25pp.com/jsondata.html)

I've wrote this test code:


    from app import AppDetailInfo
    from preprocess import get_download_url, get_base_info_from_itunes
    
    if __name__ == '__main__':
        appDetialInfo = AppDetailInfo(index=0)
        appDetialInfo.appID = '390860325'
    
        get_base_info_from_itunes(appDetialInfo)
    
        print(appDetialInfo.name)
        print(appDetialInfo.generes)
        print(appDetialInfo.bundleID)
        print(appDetialInfo.company_name)
    
        get_download_url(appDetialInfo)
    
        print(appDetialInfo.download_url)


but I still get the same error...
thanks !

**Comment by CodingForMoney** [comment]
Your code works fine for me. 

```
➜  server git:(master) ✗ python3 pre-process.py
口碑-双11狂欢节
生活、美食佳饮
com.taobao.kbmeishi
口碑网
http://r11.25pp.com/soft/2018/10/25/20181025_8680_233185556967.ipa
```

If you can't access the `25pp.com` , you could try to download all APPs using jailbreak device and the `tweak`.

**Comment by huliang2016** [comment]
so sad...

**Comment by CodingForMoney** [comment]
你在国内吗？ 为啥能上网站，却访问不了接口啊 ？😂 还是说这个网站出了什么新的防爬虫策略了？

**Comment by huliang2016** [comment]
在国内，不知道为啥。。。
我也感觉很奇怪，能访问PP助手，但是不能访问 jsondata 那个网址。。。
网站报错信息：

`
502 Bad Gateway
The proxy server received an invalid response from an upstream server. Sorry for the inconvenience.
Please report this message and include the following information to us.
Thank you very much!
`

**Comment by CodingForMoney** [comment]
直接访问这个接口是肯定不行的，要设置Header , 而且是POST接口。 

我这边依然是能走通这个接口的，说明这个接口还在，没有被封掉。 那你访问不了，可能是你网络的问题。你可以尝试换一下网络， 或者用流量试一下。

**Comment by huliang2016** [comment]
好的，谢谢大佬，麻烦大佬了，感谢！

**Comment by CodingForMoney** [comment]
如果你想要获得一些应用的信息， 我的接口实在跑不通，你可以自己尝试一下去分析 pp助手的网页和APP。

如果你只是想了解怎么批量下载APP的， 那你看后面那部分就行了， 越狱环境下在App Store上模拟操作，进行下载。

**Comment by huliang2016** [comment]
好的，感谢大佬~
